name: do something exciting
on: [push]
jobs:
  build::
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set-up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependancies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: push repo
        run: |
          git config user.name git-hub-actions
          git config user.email gav@gav
          git add .
          git commit -m "modified feed"
          git push
          
        
