name: do something exciting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run update Repo
        uses: gavinswilson/update_readme_timestamp@main
        
